use_frameworks!

platform :ios, '10.0'

target 'ModuleMovieList_Example' do
  pod 'ModuleMovieList', :path => '../'

  target 'ModuleMovieList_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
